version: "3.7"

services:
  db_devjobs:
    image: postgres
    container_name: db_devjobs
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devjobs
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  devjobs:
    build: .
    container_name: devjobs
    depends_on:
      - db_devjobs
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
